### ISSUE TITLE
Exiftool installation: No functioning version has been found

### ISSUE THREAD

**Issue by schafnoir** [JoshOBrien/exiftoolr#16]
Hi @JoshOBrien - first I wanted to thank you for maintaining this helpful wrapper for ExifTool, and I think I may be experiencing an issue similar to one that was closed in late 2021. The short summary is that I have installed version 0.2.1 from GitHub, but when I install exiftool, it appears that exiftoolr cannot then find it. Here are a few more details of my system and what I have done:

version
platform       x86_64-apple-darwin17.0     
arch           x86_64                      
os             darwin17.0                  
system         x86_64, darwin17.0          
status                                     
major          4                           
minor          2.2                         
year           2022                        
month          10                          
day            31                          
svn rev        83211                       
language       R                           
version.string R version 4.2.2 (2022-10-31)
nickname       Innocent and Trusting   

I used `devtools::install_github("JoshOBrien/exiftoolr")` to get version 0.2.1 of the package.

I then installed the exiftool software:
`exiftoolr::install_exiftool()`
`Attempting to download ExifTool from https://exiftool.org/Image-ExifTool-12.56.tar.gz
 [100%] Downloaded 5187642 bytes...`
`Installing ExifTool in /Users/UserName/Library/Application Support/org.R-project.R/R/exiftoolr`

When I check the exiftool version, the just-downloaded exiftool cannot be found:
`exiftoolr::exif_version(quiet = FALSE)`
`Trying perl command: 'perl' --version`
`Perl found at: 'perl'`
`Trying exiftool command: '' -ver`
`Trying exiftool command: 'exiftool' -ver`
`Trying exiftool command: 'perl' '/Users/UserName/Library/Application Support/org.R-project.R/R/exiftoolr/exiftool' -ver`
`Error in configure_exiftoolr(quiet = quiet) : `
`No functioning version of Exiftool has been found. To download and install a local version into the exiftoolr package, try doing install_exiftool().`

I can manually configure exiftoolr to find the installation, but this must be done every time I start RStudio:
`exifPath <- '/Users/UserName/Library/Application Support/org.R-project.R/R/exiftoolr/exiftool'`
`exiftoolr::configure_exiftoolr(
  command = exifPath
)`

`Trying perl command: 'perl' --version`
`Perl found at: 'perl'`
`Trying exiftool command: '/Users/UserName/Library/Application Support/org.R-project.R/R/exiftoolr/exiftool' -ver`
`ExifTool found at: '/Users/UserName/Library/Application Support/org.R-project.R/R/exiftoolr/exiftool'`

`exiftoolr::exif_version()
[1] "12.56"`

Looking back to the closed issue from 2021, there seemed to be a problem with having spaces in the path. In this example, macOS introduces a space in the `Application Support` folder that exiftoolr defaults to for installation. Could this be problematic? 

Thanks for your help, and I appreciate the work you've put into this package!

**Comment by JoshOBrien** [comment]
Hi @schafnoir. How frustrating! 

I don't have access to a Mac right now, which makes this a little bit harder to investigate. Will try to get my hands on one over the weekend to see for sure what's going on.

In the meanwhile, I've got a couple of thoughts:

- I doubt spaces in the path are an issue, since once you manually set the path, things work for you (despite there being a space in that path)!

- The problem seems to be that when you initially call `exif_version()`, it constructs and tries a command-line call that's prepended with `'perl'`, whereas when you set the path yourself, `configure_exiftoolr()` constructs and tries the same command without that prepended perl. The two commands are copied below:
```bash
Trying exiftool command: 'perl' '/Users/UserName/Library/Application Support/org.R-project.R/R/exiftoolr/exiftool' -ver
Trying exiftool command: '/Users/UserName/Library/Application Support/org.R-project.R/R/exiftoolr/exiftool' -ver
```
Debugging and correcting that will be easier once I'm working on a Mac.

- In the meantime, you could set the path to exiftool via the environment variable `"ET_EXIFTOOL_PATH"`. One way to do that would be to add a line like the following to your `.Renviron` file (as an alternative to setting it manually within each R session):
```bash
ET_EXIFTOOL_PATH="/Users/UserName/Library/Application Support/org.R-project.R/R/exiftoolr/exiftool"
```
For more details on where you can set environment variables like this, see `?Startup`.

HTH,

- Josh

**Comment by schafnoir** [comment]
Hi @JoshOBrien - thanks for the quick reply! I have used the `ET_EXIFTOOL_PATH` approach in the past, and I agree that approach will work to get around the issue. I just wanted to report here to ensure I wasn't missing something obvious or doing something foolish!

Cheers,
Courtney

**Comment by JoshOBrien** [comment]
Hi again, @schafnoir,

I wasn't able to find Mac to work on, but think that with cabd9a5 I've found a fix for the issue you're encountering. Would you do me the favor of updating to the latest version I've got here on GitHub, and then letting me know if that fixes the problem?

Thanks,

-- Josh

**Comment by schafnoir** [comment]
Hi @JoshOBrien - I updated the package from Github here, and as you predicted the issue has been resolved. Whatever you did, excellent work!

**Comment by JoshOBrien** [comment]
@schafnoir Super! Thanks again for the bug report and for confirming that it is indeed fixed.

**Comment by JoshOBrien** [comment]
FTR, exiftoolr version 0.2.2, now on CRAN, incorporates this bug fix.
