### ISSUE TITLE
"Error 404" and "No functioning version of Exiftool has been found"

### ISSUE THREAD

**Issue by Joao24lmeida** [JoshOBrien/exiftoolr#23]
Hi,

I have downloaded the package but when I try to download "exiftool", i get this error:
![image](https://github.com/user-attachments/assets/f1bbec52-3862-4852-a084-23acd9d9a7e7)

I tried downloading the exiftool.zip, unzipping it and renaming the resulting folder as simply exiftool, and the exiftool(-k).exe file inside it to exiftool.exe, then I moved the exiftool folder and contents to my current R install library. But got this message:
![image](https://github.com/user-attachments/assets/9549ab68-def3-492b-8bbb-522ef923e4e0)

I changed the location of the file multiple times, making sure its in my PATH directory but I still got this message. 
as an example:
![image](https://github.com/user-attachments/assets/44388a2c-8f45-4613-a958-1b99e8d2575f)

Any help would be truly appreciated and I'm sorry for the lack of Rstudio Knowledge, I'm new at this.

**Comment by TaajaT** [comment]
I am having the same issue, unfortunately. Trying to install manually with "install_exiftool" isn't working either. Using "configure_exiftoolr()" results in: "Trying exiftool command: "C:\Users\MYNAME\AppData\Roaming/R/data/R/exiftoolr/win_exe/exiftool(-k).exe" -ver" [...] "No functioning version of Exiftool has been found." despite the exe being at that exact path.

**Comment by JoshOBrien** [comment]
@Joao24lmeida and @TaajaT, thanks for the reports.

It looks like, within the last few hours, Phil Harvey has made some changes to how he distributes the Windows exiftool executables. They are now ([see here](https://exiftool.org/)) distributed as separate 32 bit and 64 bit executables. The zip files to be downloaded now include a "_32" or a "_64" in their name, which is why they aren't found by "install_exiftool()".

Furthermore, they seem to be packaged up one directory deeper *and*, even when unpacked fully, to respond slightly differently to the command (Copied by @TaajaT) that I had constructed to check the version.

None of these should be complicated to fix, but it might be a day before I can get to them. Once I do, though, I'll ping both of you to let you know that the fixed version is up on GitHub. (I will also push a revised version to CRAN, but even if they immediately accept the new version, which they typically do, it'll be another couple of days before the fixed Windows binary packages make their way out to all the mirrors.)

Thanks again for letting me know you were seeing this issue!

**Comment by JoshOBrien** [comment]
@Joao24lmeida & @TaajaT. I've gone ahead and made what I think are all the required changes. Certainly works for me now.

When you have a chance, would you mind installing the most recent version from GitHub, by doing this ...

```r
if(!require(devtools)) {install.packages("devtools")}
devtools::install_github("JoshOBrien/exiftoolr")
```

... and then seeing whether `install_exiftool()` followed by `exif_version()` indicate it's working for you as well?

**Comment by TaajaT** [comment]
It works! (exif_version() "12.89") Thank you!!

**Comment by JoshOBrien** [comment]
Super! Thanks. On its way to CRAN now.

**Comment by Joao24lmeida** [comment]
@JoshOBrien Thank you for the speedy reply, sadly it's still not working for me

![image](https://github.com/user-attachments/assets/4b9e74bd-bded-4acc-b0f6-d2da93e66ced)

**Comment by JoshOBrien** [comment]
@Joao24lmeida Thanks for checking and for the feedback. I made one more tweak that should, I think, fix the issue for you.

Would you mind trying once more with the version I just now pushed to GitHub?

**Comment by Joao24lmeida** [comment]
It worked, thank you very much!

**Comment by JoshOBrien** [comment]
@Joao24lmeida Great. Glad to hear it.

Now I'll just hope that Phil Harvey sticks with this method of distributing the Windows executables for a good long while!

**Comment by JoshOBrien** [comment]
Closing with dc09c3a, pushed to [CRAN](https://cran.r-project.org/package=exiftoolr) as package version 0.2.6.
