### ISSUE TITLE
Check for exiftool on new installation

### ISSUE THREAD

**Issue by EOGrady21** [JoshOBrien/exiftoolr#6]
I'm looking to use this package to check some image metadata within a shiny app. 

The trick is that I have to make sure the machine running the shiny app has exiftools. 

Is there a way to check that exiftool is available before attempting to run exiftoolr functionality? 

Thanks!

**Comment by JoshOBrien** [comment]
Would something like this do the trick? It will return `TRUE` if a functioning version of ExifTool (plus, if needed, Perl) is available, and otherwise `FALSE`.

```r
is_exiftool_available <- function() {
    !is.null(tryCatch(exif_version(), error = function(e) NULL))
}
```

If you are not on Windows and using the Windows executable, and want to first check whether Perl is available, you could possibly do something like this, which uses the unexported function `exiftoolr:::configure_perl()`:

```r
is_perl_available <- function() {
    !is.null(tryCatch(exiftoolr:::configure_perl(), error = function(e) NULL))
}
```

**Comment by EOGrady21** [comment]
That will work perfectly! Thanks so much for your help! 🥇

**Comment by JoshOBrien** [comment]
@EOGrady21 Great. Glad to hear that!
